// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ZJPrtlEkW2L9ilxxRxCMhYKZSTTGMC4',
    appId: '1:114714721078:android:374e18e1e0c6b180fc5197',
    messagingSenderId: '114714721078',
    projectId: 'soko-aerial-interns-app',
    storageBucket: 'soko-aerial-interns-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsW5RRnxmgt5zPIE9boAG-3sE4LKEKM5o',
    appId: '1:114714721078:ios:c96ea5fac2a1e25cfc5197',
    messagingSenderId: '114714721078',
    projectId: 'soko-aerial-interns-app',
    storageBucket: 'soko-aerial-interns-app.appspot.com',
    androidClientId: '114714721078-ktursk8uiqoieer93fik6dv7qv27rif9.apps.googleusercontent.com',
    iosClientId: '114714721078-dcco0pv45u7vtihbka2ugfnpih8pjreg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokoAerialInternsApp',
  );
}
